# Generated by Django 4.2.23 on 2025-08-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expiry_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
