# Generated by Django 4.2.23 on 2025-08-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_choice_votes_alter_poll_expiry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='creator_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['poll', 'votes'], name='poll_choice_poll_id_81c525_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['votes'], name='poll_choice_votes_01cd99_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['session_id'], name='poll_poll_session_5b0e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expiry_time'], name='poll_poll_expiry__e931ce_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active', 'expiry_time'], name='poll_poll_is_acti_37f954_idx'),
        ),
    ]
